server:
  port: 6688
  
spring:
  application: 
    name: servicecloud-config-server
  cloud:
    config:
      server:
        git:
          # 远程仓库的github地址
          uri: https://github.com/Liaoyuangui/servicecloud_config.git